a=input('Digite algo: ')
print('O tipo primitivoi desse valor é,', type (a))
print('So tem espaços?', a.isspace())
print('E um numero? ', a.isnumeric())
print('é alfanumerico?', a.isalnum())
print('É alfabético?', a.isalpha())
print('É um digito?', a.isdigit())
print('É um capitalize?', a.capitalize())
print('É um numero decimal?',a.isdecimal())